changesetBaseRefs:
  - HEAD

npmAuthToken: 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

npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/yarn-plugin-version-tools.cjs
    spec: "https://github.com/indooorsman/yarn-plugins/releases/download/v1.0.5/plugin-version-tools.js"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
