# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: 'releases/**'
    

jobs:
  build:
    if: github

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: git config --global init.defaultBranch main
    - run: corepack enable && echo $(yarn -v)
    - run: yarn plugin remove yarn-plugin-version-tools
#     - run: yarn plugin import https://github.com/indooorsman/yarn-plugins/releases/download/v1.0.5/plugin-version-tools.js
    - run: yarn plugin import version
    - run: yarn install --frozen-lockfile
    - run: yarn build
#     - run: yarn vt prerelease --preid rc
    - run: yarn version patch
    - run: git add . && git commit -m v$(yarn node -pe "require('./package.json')['version']")
    - run: yarn npm publish

